vich_uploader:
    db_driver: orm

    mappings:
        act:
            uri_prefix: '%app.path.act%'
            upload_destination: '%kernel.project_dir%/public%app.path.act%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        artist:
            uri_prefix: '%app.path.artist%'
            upload_destination: '%kernel.project_dir%/public%app.path.artist%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
